[package]
name = "hydra-sentinel-client"
version = "0.1.0"
edition = "2021"

[dependencies]
hydra-sentinel.path = "../lib/"

anyhow = { workspace = true }
backon = { workspace = true }
futures-util = { workspace = true }
humantime-serde = { workspace = true }
keepawake = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
tokio-tungstenite = { workspace = true, features = ["native-tls"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing = { workspace = true }
