[package]
name = "hydra-sentinel-server"
version = "0.1.0"
edition = "2021"

[dependencies]
hydra-sentinel.path = "../lib/"

anyhow = { workspace = true }
axum = { workspace = true, features = ["ws", "http2", "macros"] }
futures-util = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
humantime-serde = { workspace = true }
ipnet = { workspace = true, features = ["serde"] }
listenfd = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "fs"] }
tower = { workspace = true, features = ["tracing", "timeout"] }
tower-http = { workspace = true, features = ["trace", "timeout"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }
wake-on-lan = { workspace = true }

