listen_addr = "0.0.0.0:3000"
hydra_base_url = "https://hydra.nregner.net"
hydra_machines_file = "/tmp/hydra-machines"
heartbeat_timeout = "30s"
allowed_ips = ["192.168.0.0/24", "127.0.0.1/32", "100.0.0.0/8"]
github_webhook_secret_file = "/dev/null"

[[builders]]
hostName = "enceladus"
system = "aarch64-darwin"
features = ["nixos-test", "benchmark", "big-parallel"]
mac_address = "60:3e:5f:4e:4e:bc"

[[builders]]
hostName = "m3-linux-vm"
system = "aarch64-linux"
features = ["nixos-test", "benchmark", "big-parallel"]
macAddress = "60:3e:5f:4e:4e:bc"

[[builders]]
hostName = "iapetus"
system = "x86_64-linux"
features = ["nixos-test", "benchmark", "big-parallel"]
