builder_timeout = "30s"
hydra_url = "https://hydra.nregner.net"
machines_file = "/tmp/hydra-machines"
allowed_ip_ranges = [
    "192.168.0.0/24",
    # "127.0.0.1/32",
    "100.0.0.0/8",
]

[[builders]]
hostname = "enceladus"
system = "aarch64-darwin"
features = ["nixos-test", "benchmark", "big-parallel"]
mac_address = "60:3e:5f:4e:4e:bc"

[[builders]]
hostname = "m3-linux-vm"
system = "aarch64-linux"
features = ["nixos-test", "benchmark", "big-parallel"]
mac_address = "60:3e:5f:4e:4e:bc"

[[builders]]
hostname = "iapetus"
system = "x86_64-linux"
features = ["nixos-test", "benchmark", "big-parallel"]
