builder_timeout = "30s"
hydra_url = "https://hydra.nregner.net"
machines_file = "/etc/hydra/machines"

[[builders]]
host_name = "enceladus"
system = "aarch64-darwin"
features = ["nixos-test", "benchmark", "big-parallel"]
mac_address = "60:3e:5f:4e:4e:bc"

[[builders]]
host_name = "iapetus"
system = "x86_64-linux"
features = ["nixos-test", "benchmark", "big-parallel"]
